# Application URL
url=https://www.saucedemo.com/

# Login credentials
username=standard_user
password=secret_sauce

# Browser
browser=chrome

# Checkout details
firstname=Dinesh
lastname=E
postalcode=658963

# Wait timeout
timeout=10